### ISSUE TITLE
add description

### ISSUE THREAD

**Issue by retokromer** [cellar-wg/Cellar-FLAC#76]
In my opinion, we should add a description for this repository, but I do not have the permission to make (a PR for) this.

**Comment by dericed** [comment]
You can make a PR but making a fork first.

**Comment by JeromeMartinez** [comment]
> You can make a PR but making a fork first.

No PR possible for adding a description, only the repo owner can add a description.

**Comment by retokromer** [comment]
I’m afraid, I could not find a way to make a pull request to add a description and therefore I opened this issue.

**Comment by privatezero** [comment]
Not sure about what all happened to the permissions etc after the transfer to the org account - I'm travelling this week and stuck with slow/spotty mobile only, but I can take a look at this stuff once I get back stateside!

**Comment by dericed** [comment]
There is no 'credit' given to the repository description. If you're ok with contributing an uncredited description I suggest sharing a proposal within this thread for the maintainers' consideration rather than use a PR.

**Comment by retokromer** [comment]
>If you're ok with contributing

Who should be okay? If me, as not English speaker, I would have suggested the placeholder: `The Free Lossless Audio Codec (FLAC) Specification.`

**Comment by privatezero** [comment]
On review, with transfer to cellar-wg organizational account, looks like I gave up all my permissions to make changes of this sort to this repo. I believe that would have to be done by one of the people with 'owner' level privileges in cellar-wg.

**Comment by privatezero** [comment]
* that would appear to be either @mcr or @bacampbe

**Comment by retokromer** [comment]
<img width="1113" alt="screenshot 2019-02-18 at 07 33 28" src="https://user-images.githubusercontent.com/3246607/52932280-85b25280-334f-11e9-850b-5208d2868014.png">

**Comment by JeromeMartinez** [comment]
>  `The Free Lossless Audio Codec (FLAC) Specification.`

+1 (I don't have the description edition rights)

**Comment by retokromer** [comment]
I did what I could.

**Comment by JeromeMartinez** [comment]
bump on that, only the admins can edit the description, just a copy/paste of `The Free Lossless Audio Codec (FLAC) Specification.`

**Comment by retokromer** [comment]
Neither @mcr nor @bacampbe stepped in during three months…

**Comment by mcr** [comment]
Jérôme Martinez <notifications@github.com> wrote:
    > bump on that, only the admins can edit the description, just a copy/paste of
    > The Free Lossless Audio Codec (FLAC) Specification.

Sorry, what?
Are you speaking about the github description?  Are you lacking a github
permission then?    Please do not assume that I read every github thread.

**Comment by JeromeMartinez** [comment]
> Are you speaking about the github description? 

Right.

> Are you lacking a github permission then? 

Right.
I am not admin of this repo, but if someone accepts to put me as admin, I do the change :).

**Comment by mcr** [comment]
You are now an admin for this repo.
